# Database configurations

default: &default
  adapter: pg
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: db/bld-test

test:
  <<: *default
  database: db/bld-dev

production:
  <<: *default
  database: db/bld
