# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8fc2ba86ea5315781f7b3d76a80cdeed1ba4aa742304a9cff03e9521f44c9c05ebeafe1ba8123d5242b22daff79f15d8a2e3b7208aa1d678fad488806b30b105

test:
  secret_key_base: 75cf57ef339fe6bd34d4118c29ca2b1f6ad35665de25c894c8d91a17c98a50579b11640978ec698a81fb52b909418fc28114781588a37f0a80350dfe6eeb1f07

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
